app/views/auth.py
from flask import Blueprint, flash, request, render_template, redirect, url_for, abort
from flask_login import login_user, logout_user
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import InputRequired, Length
from passlib.hash import sha256_crypt
from urllib.parse import urlparse, urljoin

from app.models import Users


def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ('http', 'https') and ref_url.netloc == test_url.netloc


bp = Blueprint('auth', __name__, template_folder='templates')


# Login page
@bp.route('/login', methods=['GET', 'POST'])
def login():

    class LoginForm(FlaskForm):
        login = StringField('Login', validators=[InputRequired(), Length(max=255)])
        password = StringField('Password', validators=[InputRequired(), Length(max=255)])

    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(login=form.login.data).first()

        next = request.args.get('next')
        if not is_safe_url(next):
            return abort(400)

        if user and sha256_crypt.verify(form.password.data, user.password):
            login_user(user)
            flash('Logged in successfully')

            return redirect(url_for('home.get'))
        else:
            flash('Invalid login details')
            return render_template('login.jinja', form=form)

    elif form.is_submitted():
        for field_name, errors in form.errors.items():
            for err in errors:
                flash(f"{form._fields[field_name].label.text}: {err}", 'error')

    return render_template('login.jinja', form=form)


# Logout
@bp.route('/logout', methods=['GET'])
def logout():
    logout_user()
    return redirect(url_for('home.get'))

app/views/employee_personal.py
from flask import Blueprint, abort, render_template, flash, redirect, url_for
from flask_login import login_required, current_user

from app.app import db
from app.forms.employee import EmployeePersonalForm
from app.models import Employees, Positions

bp = Blueprint('employee_personal', __name__, template_folder='templates')


@bp.route('/employee/personal', methods=['GET', 'POST'])
@login_required
def get_post():
    if not current_user.is_authenticated or current_user.employee_id is None:
        abort(401)

    employee = Employees.query.filter_by(id=current_user.employee_id).one_or_none()
    if not employee:
        abort(400)

    position = Positions.query.filter_by(id=employee.position_id).one_or_none()
    if not position:
        abort(400)

    employee_personal_form = EmployeePersonalForm()

    if employee_personal_form.validate_on_submit():
        employee.first_name = employee_personal_form.first_name.data
        employee.last_name = employee_personal_form.last_name.data
        employee.tel_number = employee_personal_form.tel_number.data
        employee.email = employee_personal_form.email.data

        db.session.commit()
        flash('Personal information has been successfully updated.')

    elif employee_personal_form.is_submitted():
        for field_name, errors in employee_personal_form.errors.items():
            for err in errors:
                flash(f"{employee_personal_form._fields[field_name].label.text}: {err}", 'error')

        return render_template('employee_personal.jinja', employee_personal_form=employee_personal_form)

    employee_personal_form.first_name.data = employee.first_name
    employee_personal_form.last_name.data = employee.last_name
    employee_personal_form.tel_number.data = employee.tel_number
    employee_personal_form.email.data = employee.email
    employee_personal_form.position.data = position.name

    return render_template('employee_personal.jinja', employee_personal_form=employee_personal_form)

app/views/eq_reservation.py
import datetime

from flask import Blueprint, abort, flash, render_template, redirect, url_for, jsonify
from flask_login import current_user, login_required
from sqlalchemy import and_

from app.app import db
from app.forms.guest import EquipmentReservationForm
from app.models import EqCategories, Equipment, EqReservations

bp = Blueprint('eq_reservation', __name__, template_folder='templates')


@bp.route('/guest/equipment/reservation', methods=['GET', 'POST'])
@login_required
def get_post():
    if not current_user.is_authenticated or current_user.guest_id is None:
        abort(401)

    eq_res_form = EquipmentReservationForm()

    eq_categories = EqCategories.query.order_by(EqCategories.name).all()
    eq_res_form.eq_category.choices = [cat.name for cat in eq_categories]

    eq_list = Equipment.query.order_by(Equipment.name).all()
    eq_res_form.eq_name.choices = [eq.name for eq in eq_list]

    if eq_res_form.validate_on_submit():
        # Merge date and hour
        start_date = eq_res_form.start_date.data
        start_hour = eq_res_form.start_date_hour.data
        end_date = eq_res_form.end_date.data
        end_hour = eq_res_form.end_date_hour.data

        start = datetime.datetime.combine(start_date, start_hour)
        end = datetime.datetime.combine(end_date, end_hour)

        start = start - datetime.timedelta(minutes=start_hour.minute)

        if end_hour.minute != 0:
            if end_hour.hour == 23:
                end = end - datetime.timedelta(hours=end_hour.hour, minutes=end_hour.minute)
                end = end + datetime.timedelta(days=1)
            else:
                end = end + datetime.timedelta(minutes=(60 - end_hour.minute))

        # check other reservations
        eq = Equipment.query.filter_by(name=eq_res_form.eq_name.data).one_or_none()
        reserved = False
        if eq:
            reservations = EqReservations.query.filter(and_(
                EqReservations.equipment_id == eq.id,
                and_(
                    EqReservations.start_date < end,
                    EqReservations.end_date > start
                )
            )).count()

            if reservations > 0:
                reserved = True

        if not eq:
            flash('Invalid equipment name.', 'error')
        elif reserved:
            flash('Equipment not available on the selected dates.', 'error')
        else:
            eq_reservation = EqReservations(
                equipment_id=eq.id,
                guest_id=current_user.id,
                start_date=start,
                end_date=end
            )
            db.session.add(eq_reservation)
            db.session.commit()

            flash('Reservation added.')
            return redirect(url_for('eq_reservation.get_post'))

    elif eq_res_form.is_submitted():
        for field_name, errors in eq_res_form.errors.items():
            for err in errors:
                flash(f"{eq_res_form._fields[field_name].label.text}: {err}", 'error')

    return render_template('eq_reservation.jinja', eq_res_form=eq_res_form)


@bp.route('/equipment/<string:category_name>')
@login_required
def equipment(category_name: str):
    category = EqCategories.query.filter_by(name=category_name.replace('%20', ' ').capitalize()).one_or_none()

    if not category:
        abort(400)

    equipment = Equipment.query.filter_by(cat_id=category.id).all()
    return jsonify({'equipment_list': [eq.name for eq in equipment]})

app/views/guest_personal.py
from flask import Blueprint, abort, flash, render_template
from flask_login import login_required, current_user

from app.app import db
from app.forms.guest import GuestPersonalForm
from app.models import Guests

bp = Blueprint('guest_personal', __name__, template_folder='templates')


@bp.route('/guest/personal', methods=['GET', 'POST'])
@login_required
def get_post():
    if not current_user.is_authenticated or current_user.guest_id is None:
        abort(401)

    guest = Guests.query.filter_by(id=current_user.guest_id).one_or_none()
    if not guest:
        abort(400)

    guest_personal_form = GuestPersonalForm()

    if guest_personal_form.validate_on_submit():
        guest.first_name = guest_personal_form.first_name.data
        guest.last_name = guest_personal_form.last_name.data
        guest.age = guest_personal_form.age.data
        guest.tel_number = guest_personal_form.tel_number.data
        guest.email = guest_personal_form.email.data

        db.session.commit()
        flash('Personal information has been successfully updated.')

    elif guest_personal_form.is_submitted():
        for field_name, errors in guest_personal_form.errors.items():
            for err in errors:
                flash(f"{guest_personal_form._fields[field_name].label.text}: {err}", 'error')

        return render_template('guest_personal.jinja', guest_personal_form=guest_personal_form)

    guest_personal_form.first_name.data = guest.first_name
    guest_personal_form.last_name.data = guest.last_name
    guest_personal_form.age.data = guest.age
    guest_personal_form.tel_number.data = guest.tel_number
    guest_personal_form.email.data = guest.email

    return render_template('guest_personal.jinja', guest_personal_form=guest_personal_form)

app/views/home.py
from datetime import datetime

from flask import Blueprint, render_template
from flask_login import current_user

from app.models import RoomReservations, Rooms, EqReservations, Equipment, Tasks, Employees

bp = Blueprint('home', __name__, template_folder='templates')


@bp.route('/home', methods=['GET'])
@bp.route('/', methods=['GET'])
def get():
    admin_check = False

    if current_user.is_authenticated and current_user.guest_id is not None:
        room_res = RoomReservations.query.filter_by(guest_id=current_user.id).order_by(RoomReservations.start_date).all()
        room_res_list = []

        for res in room_res:
            room = Rooms.query.filter_by(id=res.room_id).first()

            res_element = {
                'room_number': room.number,
                'start_date': datetime.strftime(res.start_date, '%Y-%m-%d'),
                'end_date': datetime.strftime(res.end_date, '%Y-%m-%d'),
                'num_of_people': res.num_of_people,
                'price': room.price_per_day * (res.end_date - res.start_date).days
            }
            room_res_list.append(res_element)

        eq_res = EqReservations.query.filter_by(guest_id=current_user.id).order_by(EqReservations.start_date).all()
        eq_res_list = []

        for res in eq_res:
            equipment = Equipment.query.filter_by(id=res.equipment_id).first()

            res_element = {
                'equipment': equipment.name,
                'start_date': res.start_date,
                'end_date': res.end_date,
                'price': equipment.cost_per_hour * ((res.end_date - res.start_date).seconds//3600)
            }
            eq_res_list.append(res_element)

        return render_template('home.jinja', room_res_list=room_res_list, eq_res_list=eq_res_list, admin_check=admin_check)

    elif current_user.is_authenticated and current_user.employee_id is not None:
        tasks = Tasks.query.filter_by(employee_id=current_user.employee_id).all()
        list_of_tasks = []

        for task in tasks:
            room = Rooms.query.filter_by(id=task.room_id).first()

            task_element = {
                'room_number': room.number,
                'name': task.name,
                'description': task.description
            }
            list_of_tasks.append(task_element)

        position = Employees.query.with_entities(Employees.position_id).filter_by(id=current_user.employee_id).one_or_none()
        if position and position[0] in [1, 2]:
            admin_check = True

        return render_template('home.jinja', tasks=list_of_tasks, admin_check=admin_check)

    return render_template('home.jinja', admin_check=admin_check)

app/views/room_reservation.py
from flask import Blueprint, abort, flash, render_template, redirect, url_for
from flask_login import current_user, login_required
from sqlalchemy import and_

from app.app import db
from app.forms.guest import RoomReservationForm
from app.models import Rooms, RoomReservations

bp = Blueprint('room_reservation', __name__, template_folder='templates')


@bp.route('/guest/room/reservation', methods=['GET', 'POST'])
@login_required
def get_post():
    if not current_user.is_authenticated or current_user.guest_id is None:
        abort(401)

    rooms = Rooms.query.order_by(Rooms.id).all()

    room_res_form = RoomReservationForm()
    room_res_form.room_number.choices = [room.number for room in rooms]

    if room_res_form.validate_on_submit():
        # check other reservations
        room = Rooms.query.filter_by(number=room_res_form.room_number.data).one_or_none()
        reserved = False
        if room:
            reservations = RoomReservations.query.filter(and_(
                RoomReservations.room_id == room.id,
                and_(
                    RoomReservations.start_date < room_res_form.end_date.data,
                    RoomReservations.end_date > room_res_form.start_date.data
                )
            )).count()

            if reservations > 0:
                reserved = True

        if not room:
            flash('Invalid room number.', 'error')
        elif room_res_form.num_of_people.data > room.capacity:
            flash('Number of people exceeds room capacity.', 'error')
        elif reserved:
            flash('Room not available on the selected dates.', 'error')
        else:
            room_reservation = RoomReservations(
                guest_id=current_user.id,
                room_id=room.id,
                start_date=room_res_form.start_date.data,
                end_date=room_res_form.end_date.data,
                num_of_people=room_res_form.num_of_people.data
            )
            db.session.add(room_reservation)
            db.session.commit()

            flash('Reservation added.')
            return redirect(url_for('room_reservation.get_post'))

    elif room_res_form.is_submitted():
        for field_name, errors in room_res_form.errors.items():
            for err in errors:
                flash(f"{room_res_form._fields[field_name].label.text}: {err}", 'error')

    return render_template('room_reservation.jinja', rooms=rooms, room_res_form=room_res_form)

app/templates/base.jinja
 <!DOCTYPE html>
  <html{% block html_attribs %}{% endblock html_attribs %}>
  {%- block html %}
    <head>
      {%- block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
              crossorigin="anonymous">

        <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
        <title>{% block title %}{{ title|default("HotelDB", true) }}{% endblock title %}</title>

        <!-- JQUERY -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"
                integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
                crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
              integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
              crossorigin="anonymous" referrerpolicy="no-referrer" />

        <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>

      {%- endblock head %}
    </head>
    <body{% block body_attribs %} class="d-flex flex-column min-vh-100 bg-light" {% endblock body_attribs %}>
    {% block navbar %}
        <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('home.get') }}">
                    <img src="{{ url_for('static', filename = 'img/logo_smaller.png') }}" alt=""
                         class="rounded">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('home.get') }}">Home</a>
                        </li>
                        {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}" tabindex="-1">Log out</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}" tabindex="-1">Log in</a>
                        </li>
                        {% endif %}
                        {% if current_user.is_authenticated and current_user.guest_id != none %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('guest_personal.get_post') }}" tabindex="-1">Personal information</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('room_reservation.get_post') }}" tabindex="-1">Room reservation</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('eq_reservation.get_post') }}" tabindex="-1">Equipment reservation</a>
                        </li>
                        {% elif current_user.is_authenticated and current_user.employee_id != none %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('employee_personal.get_post') }}" tabindex="-1">Personal information</a>
                        </li>
                        {% endif %}
                        {% if current_user.is_authenticated and current_user.employee_id != none and is_admin == True %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('admin.index') }}" tabindex="-1">ADMIN PANEL</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    {%- endblock navbar %}

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div id="alerts">
                {% for category, message in messages %}
                    {% if category == 'error' %}
                        <div class="alert alert-danger">
                            {{ message }}
                            <button type="button" class="btn-close float-end" aria-label="Close"
                                    onclick=delete_flash(this)></button>
                        </div>

                    {% else %}
                        <div class="alert alert-primary">
                            {{ message }}
                            <button type="button" class="btn-close float-end" aria-label="Close"
                                    onclick=delete_flash(this)></button>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}

    {% block body -%}
        {% block content -%}
        {%- endblock content %}

        {% block scripts %}
        {%- endblock scripts %}
    {%- endblock body %}

    <script>
      function delete_flash(flash){
        $(flash).parent().remove();
      }
    </script>

    </body>
  {%- endblock html %}
  </html>

app/templates/employee_personal.jinja
{% extends "base.jinja" %}

{% block content %}
  <div class="justify-content-center row">
  <div class="col-4">
    <div class="card text-center mx-3 my-3">
      <div class="card-header">
        <h3 class="card-title">Personal information</h3>
      </div>
      <div class="card-body">
        <form method="POST" action="{{ url_for('employee_personal.get_post') }}">
          {{ employee_personal_form.csrf_token }}

          <div class="form-floating mb-3">
            {{ employee_personal_form.first_name(class_="form-control") }}
            <label for="floatingInput">First name</label>
          </div>

          <div class="form-floating mb-3">
            {{ employee_personal_form.last_name(class_="form-control") }}
            <label for="floatingInput">Last name</label>
          </div>

          <div class="form-floating mb-3">
            {{ employee_personal_form.email(class_="form-control") }}
            <label for="floatingInput">Email</label>
          </div>

          <div class="form-floating mb-3">
            {{ employee_personal_form.tel_number(class_="form-control") }}
            <label for="floatingInput">Phone number</label>
          </div>

          <div class="form-floating">
            {{ employee_personal_form.position(class_="form-control") }}
            <label for="floatingInput">Position</label>
          </div>

          <button type="submit" class="btn btn-lg btn-primary mt-4 mb-2">Update</button>
        </form>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

app/templates/eq_reservation.jinja
{% extends "base.jinja" %}

{% block content %}
  <div class="justify-content-center row">
  <div class="col-4">
    <div class="card text-center mx-3 my-3">
      <div class="card-header">
        <h3 class="card-title">Equipment reservation</h3>
      </div>
      <div class="card-body">
        <form method="POST" action="{{ url_for('eq_reservation.get_post') }}">
          {{ eq_res_form.csrf_token }}

          <div class="form-floating mb-3">
            {{ eq_res_form.eq_category(class_="form-control", id_="eq_category") }}
            <label for="floatingInput">Category</label>
          </div>

          <div class="form-floating mb-3">
            {{ eq_res_form.eq_name(class_="form-control", id_="eq_name") }}
            <label for="floatingInput">Equipment</label>
          </div>

          <div class="row">
            <div class="col-8 form-floating mb-3">
              {{ eq_res_form.start_date(class_="form-control") }}
              <label style="margin-left: 15px" for="floatingInput">Start date</label>
            </div>
            <div class="col-4 form-floating mb-3">
              {{ eq_res_form.start_date_hour(class_="form-control") }}
              <label style="margin-left: 15px" for="floatingInput">Start hour</label>
            </div>
          </div>

          <div class="row">
            <div class="col-8 form-floating mb-3">
              {{ eq_res_form.end_date(class_="form-control") }}
              <label style="margin-left: 15px" for="floatingInput">End date</label>
            </div>
            <div class="col-4 form-floating mb-3">
              {{ eq_res_form.end_date_hour(class_="form-control") }}
              <label style="margin-left: 15px" for="floatingInput">End hour</label>
            </div>
          </div>
          <button type="submit" class="btn btn-lg btn-primary mt-4 mb-2">Make a reservation</button>
        </form>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

{% block scripts %}
  <script>
    $().ready(function () {
      let eqCategorySelect = document.getElementById('eq_category');
      let eqNameSelect = document.getElementById('eq_name');

      fetch('/equipment/' + eqCategorySelect.value.toLowerCase()).then(function (response) {
        response.json().then(function (data) {
          let optionHTML = '';

          for (let eq of data.equipment_list) {
              optionHTML += '<option value="' + eq + '">' + eq + '</option>';
          }

          eqNameSelect.innerHTML = optionHTML;
        })
      });

      eqCategorySelect.onchange = function () {
        let category = eqCategorySelect.value;

        fetch('/equipment/' + category.toLowerCase()).then(function (response) {
          response.json().then(function (data) {
            let optionHTML = '';

            for (let eq of data.equipment_list) {
                optionHTML += '<option value="' + eq + '">' + eq + '</option>';
            }

            eqNameSelect.innerHTML = optionHTML;
          })
        });
      }
    });
</script>
{% endblock %}

app/templates/guest_personal.jinja
{% extends "base.jinja" %}

{% block content %}
  <div class="justify-content-center row">
  <div class="col-4">
    <div class="card text-center mx-3 my-3">
      <div class="card-header">
        <h3 class="card-title">Personal information</h3>
      </div>
      <div class="card-body">
        <form method="POST" action="{{ url_for('guest_personal.get_post') }}">
          {{ guest_personal_form.csrf_token }}

          <div class="form-floating mb-3">
            {{ guest_personal_form.first_name(class_="form-control") }}
            <label for="floatingInput">First name</label>
          </div>

          <div class="form-floating mb-3">
            {{ guest_personal_form.last_name(class_="form-control") }}
            <label for="floatingPassword">Last name</label>
          </div>

          <div class="form-floating mb-3">
            {{ guest_personal_form.age(class_="form-control") }}
            <label for="floatingPassword">Age</label>
          </div>

          <div class="form-floating mb-3">
            {{ guest_personal_form.email(class_="form-control") }}
            <label for="floatingPassword">Email</label>
          </div>

          <div class="form-floating">
            {{ guest_personal_form.tel_number(class_="form-control") }}
            <label for="floatingPassword">Phone number</label>
          </div>

          <button type="submit" class="btn btn-lg btn-primary mt-4 mb-2">Update</button>
        </form>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

app/templates/home.jinja
{% extends "base.jinja" %}
{% set is_admin = admin_check %}

{% block content %}

  {% if not current_user.is_authenticated %}
    <h2 class="text-center">Welcome!</h2>
    <h3 class="text-center">Please <a href="{{ url_for('auth.login') }}">log in</a> to use the service.</h3>

  {% elif current_user.guest_id != none %}

    <div class="justify-content-center row">
    <div class="col-4">
      <div class="card text-center mx-3 my-3">
        <div class="card-header">
          <h3 class="card-title">Room reservations</h3>
        </div>
        <div class="card-body">
           <table class="table">
            <thead>
              <tr>
                <th scope="col">Room number</th>
                <th scope="col">Start date</th>
                <th scope="col">End date</th>
                <th scope="col">Num. of people</th>
                <th scope="col">Price</th>
              </tr>
            </thead>
            <tbody>
              {% for item in room_res_list %}
                <tr>
                  <td>{{ item.room_number }}</td>
                  <td>{{ item.start_date }}</td>
                  <td>{{ item.end_date }}</td>
                  <td>{{ item.num_of_people }}</td>
                  <td>{{ item.price }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="col-4">
      <div class="card text-center mx-3 my-3">
        <div class="card-header">
          <h3 class="card-title">Equipment reservations</h3>
        </div>
        <div class="card-body">
           <table class="table">
            <thead>
              <tr>
                <th scope="col">Equipment</th>
                <th scope="col">Start date</th>
                <th scope="col">End date</th>
                <th scope="col">Price</th>
              </tr>
            </thead>
            <tbody>
              {% for item in eq_res_list %}
                <tr>
                  <td>{{ item.equipment }}</td>
                  <td>{{ item.start_date }}</td>
                  <td>{{ item.end_date }}</td>
                  <td>{{ item.price }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    </div>

  {% elif current_user.employee_id != none %}
    <div class="justify-content-center row">
    <div class="col-4">
      <div class="card text-center mx-3 my-3">
        <div class="card-header">
          <h3 class="card-title">Tasks</h3>
        </div>
        <div class="card-body">
           <table class="table">
            <thead>
              <tr>
                <th scope="col">Room number</th>
                <th scope="col">Task</th>
                <th scope="col">Description</th>
              </tr>
            </thead>
            <tbody>
              {% for item in tasks %}
                <tr>
                  <td>{{ item.room_number }}</td>
                  <td>{{ item.name }}</td>
                  <td>{{ item.description }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    </div>
  {% endif %}
{% endblock %}

app/templates/login.jinja
{% extends "base.jinja" %}

{% block content %}

    <div class="container text-center col-3 mx-auto rounded">
      <main class="form-signin">
      <form method="POST" action="{{ url_for('auth.login') }}">
        <img class="mb-4 mt-2 rounded" src="{{ url_for('static', filename = 'img/logo_small.png') }}" alt="" >
        <h1 class="h3 mb-3 fw-normal">Login</h1>

        {{ form.csrf_token }}

        <div class="form-floating mb-3">
          {{ form.login(class_="form-control", id_="floatingInput", type_="login") }}
          <label for="floatingInput">username</label>
        </div>

        <div class="form-floating">
          {{ form.password(class_="form-control", id_="floatingPassword", type_="password") }}
          <label for="floatingPassword">password</label>
        </div>

        <button type="submit" class="btn btn-lg btn-primary mt-4 mb-2">Log In</button>
      </form>
      </main>
    </div>

{% endblock %}